kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alice-admin
subjects:
- kind: User
  name: alice
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io

